version: '3'

services:
  

  php:
    image: php:8.2-fpm
    container_name: PHP
    volumes:
      - ./www:/var/www/html
    networks:
      - redproyecto
    command: bash -c "docker-php-ext-install pdo_mysql && php-fpm"

  mariadb:
    build: ./mariadb
    container_name: MARIADB
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql
      - ./mariadb/insert_users.sql:/docker-entrypoint-initdb.d/insert_users.sql
      - ./mariadb/BDPRUEBA.sql:/docker-entrypoint-initdb.d/BDPRUEBA.sql
    ports:
      - "3306:3306"
    networks:
      - redproyecto

  nginx:
    image: nginx:stable-perl
    container_name: NGINX
    ports:
      - "80:80"
    volumes:
      - ./www:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - redproyecto
volumes:
  db_data: 
    driver: local
    name: Etravia

networks:
  redproyecto:
    driver: bridge
