version: '3'

services:
  

  php:
    image: php:8.2-fpm
    volumes:
      - ./www:/var/www/html
    networks:
      - redproyecto
    command: bash -c "docker-php-ext-install pdo_mysql && php-fpm"

  mariadb:
    build: ./mariadb
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - redproyecto

  nginx:
    image: nginx:stable-perl
    ports:
      - "80:80"
    volumes:
      - ./www:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - redproyecto

volumes:
  db_data: 
    driver: local

networks:
  redproyecto:
    driver: bridge
