CREATE DATABASE DAWVIAN_USERS; -- BASE DE DATOS DE USUARIOS
USE DAWVIAN_USERS;

CREATE TABLE IF NOT EXISTS USERS(
    USER_ID INT NOT NULL AUTO_INCREMENT,
    USER_NAME VARCHAR(20) NOT NULL UNIQUE,
    USER_PASSWORD VARCHAR(30) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    BIRTH_DATE DATE NOT NULL,
    CONSTRAINT USERS_PK PRIMARY KEY (USER_ID)
);