CREATE DATABASE EJEMPLO; -- BASE DE DATOS DE USUARIOS
USE EJEMPLO;

CREATE TABLE IF NOT EXISTS PLAYERS(
    PLAYER_ID INT NOT NULL AUTO_INCREMENT,
    PLAYER_NAME VARCHAR(14) NOT NULL UNIQUE,
    USER_ID INT NOT NULL,
    CONSTRAINT PLAYERS_PK PRIMARY KEY (PLAYER_ID,USER_ID)
);

CREATE TABLE IF NOT EXISTS TOWN(
    TOWN_ID INT NOT NULL AUTO_INCREMENT,
    PLAYER_ID INT NOT NULL,
    WOOD INT NOT NULL CHECK (WOOD <= 500),
    FOOD INT NOT NULL CHECK (FOOD <= 500),
    STONE INT NOT NULL CHECK (STONE <= 500),
    IRON INT NOT NULL CHECK (IRON <= 500),
    CONSTRAINT TOWN_PK PRIMARY KEY (TOWN_ID),
    FOREIGN KEY (PLAYER_ID) REFERENCES PLAYERS(PLAYER_ID)
);

CREATE TABLE IF NOT EXISTS TOWN_BUILDINGS(
    TOWN_ID INT NOT NULL,
    BUILDING VARCHAR(50) NOT NULL,
    FOREIGN KEY (TOWN_ID) REFERENCES TOWN(TOWN_ID)
);

CREATE TABLE IF NOT EXISTS MAP(
    SQUARE_ID INT NOT NULL,
    POS_X INT NOT NULL,
    POS_Y INT NOT NULL,
    PLAYER_ID INT,
    TOWN_ID INT,
    CONSTRAINT MAP_PK PRIMARY KEY (SQUARE_ID),
    FOREIGN KEY (TOWN_ID) REFERENCES TOWN(TOWN_ID),
    FOREIGN KEY (PLAYER_ID) REFERENCES PLAYERS(PLAYER_ID)
);

CREATE TABLE IF NOT EXISTS ARMY(
    PLAYER_ID INT NOT NULL,
    ARMY_ID INT AUTO_INCREMENT,
    POSITION INT NOT NULL,
    SWORDMAN INT NOT NULL,
    PIKEMAN INT NOT NULL,
    ARCHER INT NOT NULL,
    L_CAVALRY INT NOT NULL,
    H_CAVALRY INT NOT NULL,
    CONSTRAINT ARMY_ID PRIMARY KEY (ARMY_ID),
    FOREIGN KEY (PLAYER_ID) REFERENCES PLAYERS(PLAYER_ID)
);

CREATE TABLE IF NOT EXISTS LETTER(
    SENDER_ID INT NOT NULL,
    RECEIVER_ID INT NOT NULL,
    CONTENT VARCHAR (1000),
    FOREIGN KEY (SENDER_ID) REFERENCES PLAYERS(PLAYER_ID),
    FOREIGN KEY (RECEIVER_ID) REFERENCES PLAYERS(PLAYER_ID)
);

CREATE TABLE IF NOT EXISTS BATTLE_LOG(
    ATT_ID INT NOT NULL,
    DEF_ID INT NOT NULL,
    FOREIGN KEY (ATT_ID) REFERENCES PLAYERS(PLAYER_ID),
    FOREIGN KEY (DEF_ID) REFERENCES PLAYERS(PLAYER_ID)
);

