CREATE DATABASE USERS_DB; -- BASE DE DATOS DE USUARIOS
USE USERS_DB;

CREATE TABLE IF NOT EXISTS USERS(
    USER_ID INT NOT NULL AUTO_INCREMENT,
    USER_NAME VARCHAR(20) NOT NULL UNIQUE,
    USER_PASSWORD VARCHAR(30) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL UNIQUE,
    BIRTH_DATE DATE NOT NULL,
    MODERATOR BOOLEAN NOT NULL, 
    CONSTRAINT USERS_PK PRIMARY KEY (USER_ID)
);

CREATE TABLE IF NOT EXISTS WORLDSTATUS(
    WORLD_NAME VARCHAR(255) NOT NULL,
    WORLD_DESC VARCHAR(255) NOT NULL,
    WORLD_STATUS VARCHAR(100) NOT NULL,
    CONSTRAINT WORLD_NAME_PK PRIMARY KEY (WORLD_NAME)
);

insert into USERS (USER_NAME, USER_PASSWORD, EMAIL, BIRTH_DATE, MODERATOR) values ("admin","admin","mail@example.com","2000-01-01",TRUE);