CREATE DATABASE USERS_DB; -- BASE DE DATOS DE USUARIOS
USE USERS_DB;

CREATE TABLE IF NOT EXISTS USERS(
    USER_ID INT NOT NULL AUTO_INCREMENT,
    USER_NAME VARCHAR(14) NOT NULL UNIQUE,
    USER_PASSWORD VARCHAR(30) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL UNIQUE,
    BIRTH_DATE DATE NOT NULL,
    MODERATOR BOOLEAN NOT NULL, 
    BANNED BOOLEAN NOT NULL,
    CONSTRAINT USERS_PK PRIMARY KEY (USER_ID)
);

CREATE TABLE IF NOT EXISTS WORLDSTATUS(
    WORLD_NAME VARCHAR(255) NOT NULL,
    WORLD_ID VARCHAR(255) NOT NULL,
    WORLD_STATUS VARCHAR(100) NOT NULL,
    WORLD_SIZE INT NOT NULL,
    WORLD_MAXPLAYERS INT NOT NULL,
    CONSTRAINT WORLD_ID_PK PRIMARY KEY (WORLD_ID)
);

CREATE TABLE IF NOT EXISTS TICKETS(
    TICKET_ID INT NOT NULL AUTO_INCREMENT,
    EMAIL VARCHAR(255) NOT NULL,
    CONTENT VARCHAR(1000) NOT NULL,
    CONSTRAINT USERS_PK PRIMARY KEY (TICKET_ID)
);


insert into USERS (USER_NAME, USER_PASSWORD, EMAIL, BIRTH_DATE, MODERATOR,BANNED) values ("admin","admin","mail@example.com","2000-01-01",TRUE,FALSE);